services:
  - type: web
    name: api-backend
    env: python
    rootDir: apps/api
    buildCommand: |
      python -V
      pip install --upgrade pip
      pip install --no-cache-dir --default-timeout=120 --retries 5 -r requirements.txt
    startCommand: PYTHONPATH=. uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-10000}
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fcdb
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: S3_ENDPOINT
        value: https://s3.amazonaws.com
      - key: S3_REGION
        value: us-east-1
      - key: S3_BUCKET
        value: your-bucket-name
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: REPLICATE_MODEL
        value: owner/model:version
      - key: REPLICATE_WEBHOOK_SECRET
        sync: false
      - key: CORS_ALLOW_ORIGINS
        value: "*"

  - type: worker
    name: celery-worker
    env: python
    rootDir: apps/worker
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A worker worker --loglevel=INFO --concurrency=2
    plan: starter
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: API_BASE_URL
        fromService:
          type: web
          name: api-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: S3_ENDPOINT
        value: https://s3.amazonaws.com
      - key: S3_REGION
        value: us-east-1
      - key: S3_BUCKET
        value: your-bucket-name
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: REPLICATE_MODEL
        value: labprototypes/tnkfwm2:<your_version_sha>

  # ---- REDIS (Key Value) ----
  - type: redis
    name: redis
    ipAllowList: []

databases:
  - name: fcdb               # <— новое имя (НЕ начинается с pg)
    plan: basic-256mb
    postgresMajorVersion: '17'
